# Generated by Django 3.0.5 on 2020-04-08 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repertoire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover_file',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='album',
            name='cover_url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='mbid',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='area',
            name='country_code',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='iso-3166-1-code'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='begin',
            field=models.DateField(blank=True, null=True, verbose_name='Date of persons birth/Date of group formation'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='end',
            field=models.DateField(blank=True, null=True, verbose_name='Death of person/Group dissolved - blank if still together'),
        ),
        migrations.AlterField(
            model_name='track',
            name='mbid',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
