# Generated by Django 3.0.5 on 2020-04-08 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repertoire', '0002_auto_20200408_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='repertoire.Area'),
        ),
    ]
