# Generated by Django 3.0.5 on 2020-04-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repertoire', '0003_auto_20200408_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ManyToManyField(to='repertoire.Artist'),
        ),
    ]
