# Generated by Django 3.0.5 on 2020-04-08 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repertoire', '0004_album_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='name',
            field=models.CharField(default='Playlist', max_length=512),
            preserve_default=False,
        ),
    ]
