# Generated by Django 3.0.5 on 2020-04-17 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('repertoire', '0008_apikey_shown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='release',
            field=models.DateField(blank=True, null=True, verbose_name='First release of Album'),
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=128, verbose_name='Setting Identifier')),
                ('data', models.TextField(verbose_name='Data holding identifier')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
