# Generated by Django 3.0.5 on 2020-04-17 15:54

from django.db import migrations, models
import repertoire.models


class Migration(migrations.Migration):

    dependencies = [
        ('repertoire', '0010_area_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='audio',
            field=models.FileField(blank=True, help_text='Allowed type - .mp3, .wav, .ogg', null=True, upload_to=repertoire.models.audio_path, verbose_name='Audio File'),
        ),
    ]
