# Generated by Django 3.1.7 on 2021-02-26 13:30

from django.db import migrations, models
import django.db.models.deletion
import repertoire.models


class Migration(migrations.Migration):

    dependencies = [
        ('repertoire', '0010_area_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='type',
            field=models.CharField(choices=[('P', 'Person'), ('G', 'Group'), ('O', 'Orchestra'), ('C', 'Choir'), ('F', 'Character'), ('E', 'Other')], max_length=1, verbose_name='Type of Artist (Person/Group/etc.)'),
        ),
        migrations.AlterField(
            model_name='track',
            name='album',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='repertoire.album', verbose_name='Track in Album'),
        ),
        migrations.AlterField(
            model_name='track',
            name='artist',
            field=models.ManyToManyField(blank=True, to='repertoire.Artist', verbose_name='From Artist'),
        ),
        migrations.AlterField(
            model_name='track',
            name='audio',
            field=models.FileField(blank=True, help_text='Allowed type - .mp3, .wav, .ogg', null=True, upload_to=repertoire.models.audio_path, verbose_name='Audio File'),
        ),
    ]
