# Generated by Django 3.1.7 on 2021-02-26 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repertoire', '0011_auto_20210226_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='repertoire.album', verbose_name='Track in Album'),
        ),
        migrations.AlterField(
            model_name='track',
            name='artist',
            field=models.ManyToManyField(blank=True, null=True, to='repertoire.Artist', verbose_name='From Artist'),
        ),
    ]
