FROM python:slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV PYTHONUNBUFFERED 1

# Set work directory
WORKDIR /oss_server

EXPOSE 8000

# Copy project
COPY Pipfile Pipfile.lock README.md LICENSE start-server.sh oss_server /oss_server/

VOLUME /oss_server/db

#Install Pillow dependencies
RUN apt update \
    && apt install python-pillow -y \
    && apt install git -y \
    && pip install pipenv \
    && pipenv install --system \
    && python manage.py makemigrations --noinput \
    && python manage.py collectstatic --noinput
CMD sh -c "python manage.py makemigrations && gunicorn --bind :8000 --workers 3 oss_server.wsgi"
