version: '3'

services:
  ossdb:
    image: postgres:alpine
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    restart: always
  oss_server:
    build: .
    command: ./start-server.sh
    volumes:
      - .:/oss_server
    ports:
      - "8000:8000"
    environment:
      - USE_POSTGRESQL=1
    depends_on:
      - ossdb
    restart: always