version: '3.3'
services:
    oss-server:
        ports:
            - '8099:8000'
        container_name: oss-server
        volumes:
          - type: volume
            source: oss-server-db
            target: /oss_server/db
        environment:
            - DJANGO_HOST=put-your-domain-here.example.com
            - ACOUSTID_API_KEY=get-your-own-api-key-at-https://acoustid.org/new-application
        image: 'opensoundstream/oss-server:alpine'
volumes:
    oss-server-db: