name: Docker Image CI

on:
  push:
    branches: [ master ]
  repository_dispatch:
    types: [build]
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Add name and email for git changes
      run: git config --global user.email "github@anjomro.de && git config --global user.name "anjomro"
    - name: Update submodules
      run: git submodule foreach git pull origin master --allow-unrelated-histories
    - name: Add changes of submodules
      run: git add oss_server/web_interface/oss-web/
    - name: Commit and Push changes in oss-web submodule
      uses: stefanzweifel/git-auto-commit-action@v4.1.2
      with:
        commit_message: Updated oss-web submodule
        branch: master
        repository: .
        commit_user_name: anjomro
        commit_user_email: github@anjomro.de
        commit_author: anjomro <github@anjomro.de>
    - name: Build the Docker slim image
      run: docker build . --file Dockerfile.slim --tag opensoundstream/oss-server:slim
    - name: Build the Docker alpine image
      run: docker build . --file Dockerfile --tag opensoundstream/oss-server:alpine
    - name: Login into dockerhub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Push the Docker slim image to Dockerhub
      run: docker push opensoundstream/oss-server:slim
    - name: Push the Docker alpine image to Dockerhub
      run: docker push opensoundstream/oss-server:alpine
