name: Docker Image CI

on:
  push:
    branches: [ master ]
  repository_dispatch:
    types: [build]
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: Update oss-web submodule
      run: git submodule update --remote
    #- name: Build the Docker slim image
    #  run: docker build . --file Dockerfile.slim --tag opensoundstream/oss-server:slim
    - name: Build the Docker alpine image
      run: docker build . --file Dockerfile --tag opensoundstream/oss-server:alpine
    - name: Login into dockerhub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    #- name: Push the Docker slim image to Dockerhub
    #  run: docker push opensoundstream/oss-server:slim
    - name: Push the Docker alpine image to Dockerhub
      run: docker push opensoundstream/oss-server:alpine
