name: Docker Image CI

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:

  build-push-docker:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Push alpine image to Docker Hub
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: opensoundstream/oss-server
        tag_with_sha: true
        add_git_labels: true
        tags: alpine
    - name: Push slim image to Docker Hub
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: opensoundstream/oss-server
        dockerfile: Dockerfile.slim
        tag_with_sha: true
        add_git_labels: true
        tags: slim
    - name: Push alpine image to Github Packages
      uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: opensoundstream/oss-server/alpine
        tag_with_sha: true
        add_git_labels: true
        tags: alpine
    - name: Push slim image to Github Packages
      uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: opensoundstream/oss-server
        dockerfile: Dockerfile.slim
        tag_with_sha: true
        add_git_labels: true
        tags: slim
